version: "3.7"
services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: culinario
    ports:
      - 5432:5432
